version: '3'

# TODO
#   - add `depends_on:`
#   - add top-level `volumes:`

networks:
  iredmail-net:
    external: false

volumes:
  vol_ssl:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/zhb/Docker/ssl
  vol_mysql_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/zhb/Docker/data/mysql
  vol_clamav_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/zhb/Docker/data/clamav

services:
  iredmail-mariadb:
    build:
      dockerfile: Dockerfiles/mariadb
      context: .
    image: iredmail-mariadb:latest
    container_name: iredmail-mariadb
    ports:
      - 3306
    networks:
      - iredmail-net
    volumes:
      - vol_mysql_db:/var/lib/mysql

  iredmail-clamav:
    build:
      dockerfile: Dockerfiles/clamav
      context: .
    image: iredmail-clamav:latest
    container_name: iredmail-clamav
    ports:
      - 3310
    networks:
      - iredmail-net
    volumes:
      - vol_clamav_db:/var/lib/clamav

  iredmail-dovecot:
    build:
      dockerfile: Dockerfiles/dovecot
      context: .
    image: iredmail-dovecot:latest
    container_name: iredmail-dovecot
    ports:
      - 110
      - 995
      - 143
      - 993
      - 4190
      - 24
      - 12340
      - 24242
    networks:
      - iredmail-net
    depends_on:
      - iredmail-mariadb
    volumes:
      - vol_ssl:/opt/iredmail/ssl
