version: '3'

# TODO
#   - add `depends_on:`
#   - add top-level `volumes:`

networks:
  iredmail-net:
    external: false

services:
  iredmail-mariadb:
    build:
      dockerfile: Dockerfiles/mariadb
      context: .
    image: iredmail-mariadb:latest
    container_name: iredmail-mariadb
    ports:
      - 3306
    networks:
      - iredmail-net
    volumes:
      - ./iredmail/data/mysql-db:/var/lib/mysql

  iredmail-clamav:
    build:
      dockerfile: Dockerfiles/clamav
      context: .
    image: iredmail-clamav:latest
    container_name: iredmail-clamav
    ports:
      - 3310
    networks:
      - iredmail-net
    volumes:
      - ./iredmail/data/clamav-db:/var/lib/clamav

  iredmail-dovecot:
    build:
      dockerfile: Dockerfiles/dovecot
      context: .
    image: iredmail-dovecot:latest
    container_name: iredmail-dovecot
    ports:
      - 110
      - 995
      - 143
      - 993
      - 4190
      - 24
      - 12340
      - 24242
    networks:
      - iredmail-net
    depends_on:
      - iredmail-mariadb
    volumes:
      - ./iredmail/ssl:/opt/iredmail/ssl
