version: '3'

# TODO
#   - add `depends_on:`
#   - add top-level `volumes:`

networks:
  iredmail-net:
    external: false

volumes:
  vol_ssl:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUME_SSL:-/Users/zhb/Docker/ssl}
  vol_mysql_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/zhb/Docker/data/mysql
  vol_clamav_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/zhb/Docker/data/clamav
  vol_mlmmj_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/zhb/Docker/data/mlmmj
  vol_mlmmj_archive:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/zhb/Docker/data/mlmmj-archive
  vol_imapsieve_copy:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/zhb/Docker/data/imapsieve_copy

services:
  iredmail-mariadb:
    image: mariadb:10.4
    container_name: iredmail-mariadb
    env_file:
      - env.defaults
    ports:
      - 3306
    networks:
      - iredmail-net
    volumes:
      - vol_mysql_db:/var/lib/mysql

  iredmail-clamav:
    build:
      dockerfile: Dockerfiles/clamav
      context: .
    image: iredmail-clamav:latest
    container_name: iredmail-clamav
    env_file:
      - env.defaults
    ports:
      - 3310
    networks:
      - iredmail-net
    volumes:
      - vol_clamav_db:/var/lib/clamav

  iredmail-dovecot:
    build:
      dockerfile: Dockerfiles/dovecot
      context: .
    image: iredmail-dovecot:latest
    container_name: iredmail-dovecot
    env_file:
      - env.defaults
    ports:
      - 110
      - 995
      - 143
      - 993
      - 4190
      - 24
      - 12340
      - 24242
    networks:
      - iredmail-net
    depends_on:
      - iredmail-mariadb
    volumes:
      - vol_ssl:/opt/iredmail/ssl

  iredmail-postfix:
    build:
      dockerfile: Dockerfiles/postfix
      context: .
    image: iredmail-postfix:latest
    container_name: iredmail-postfix
    env_file:
      - env.defaults
    ports:
      - 25
      - 587
      - 465
    networks:
      - iredmail-net
    depends_on:
      - iredmail-mariadb
    volumes:
      - vol_ssl:/opt/iredmail/ssl
      - vol_mlmmj_data:/var/vmail/mlmmj
      - vol_mlmmj_archive:/var/vmail/mlmmj-archive
