# Require at least version '3.5' to set custom network name.
version: '3.5'

# TODO
#   - add `depends_on:`
#   - add top-level `volumes:`

networks:
  iredmail_net:
    external: false
    name: iredmail_net

volumes:
  vol_custom_conf_dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/zhb/Docker/custom
  vol_ssl:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUME_SSL:-/Users/zhb/Docker/ssl}
  vol_mysql_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/zhb/Docker/data/mysql
  vol_clamav_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/zhb/Docker/data/clamav
  vol_mlmmj_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/zhb/Docker/data/mlmmj
  vol_mlmmj_archive:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/zhb/Docker/data/mlmmj-archive
  vol_imapsieve_copy:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/zhb/Docker/data/imapsieve_copy

services:
  iredmail_mariadb:
    image: mariadb:10.4
    container_name: iredmail_mariadb
    env_file:
      - env.defaults
      - env.custom
    ports:
      - 3306:3306
    volumes:
      - vol_mysql_db:/var/lib/mysql
      - vol_custom_conf_dir:/opt/iredmail/custom
    networks:
      iredmail_net:
        aliases:
          - iredmail_mariadb

  iredmail_clamav:
    build:
      dockerfile: Dockerfiles/clamav
      context: .
    image: iredmail_clamav:latest
    container_name: iredmail_clamav
    env_file:
      - env.defaults
      - env.custom
    ports:
      - 3310:3310
    volumes:
      - vol_clamav_db:/var/lib/clamav
    networks:
      iredmail_net:
        aliases:
          - iredmail_clamav

  iredmail_dovecot:
    build:
      dockerfile: Dockerfiles/dovecot
      context: .
    image: iredmail_dovecot:latest
    container_name: iredmail_dovecot
    env_file:
      - env.defaults
      - env.custom
    ports:
      - 110:110
      - 995:995
      - 143:143
      - 993:993
      - 4190:4190
      - 24:24
      - 12340:12340
      - 24242:24242
    volumes:
      - vol_ssl:/opt/iredmail/ssl
      - vol_imapsieve_copy:/var/vmail/imapsieve_copy
      - vol_custom_conf_dir:/opt/iredmail/custom
    depends_on:
      - iredmail_mariadb
    networks:
      iredmail_net:
        aliases:
          - iredmail_dovecot

  iredmail_postfix:
    build:
      dockerfile: Dockerfiles/postfix
      context: .
    image: iredmail_postfix:latest
    container_name: iredmail_postfix
    env_file:
      - env.defaults
      - env.custom
    ports:
      - 25:25
      - 587:587
      - 465:465
    volumes:
      - vol_ssl:/opt/iredmail/ssl
      - vol_mlmmj_data:/var/vmail/mlmmj
      - vol_mlmmj_archive:/var/vmail/mlmmj-archive
      - vol_custom_conf_dir:/opt/iredmail/custom
    depends_on:
      - iredmail_mariadb
      # we need sasl auth service offered by Dovecot.
      - iredmail_dovecot
    networks:
      iredmail_net:
        aliases:
          - iredmail_postfix

  iredmail_iredapd:
    build:
      dockerfile: Dockerfiles/iredapd
      context: .
    image: iredmail_iredapd:latest
    container_name: iredmail_iredapd
    env_file:
      - env.defaults
      - env.custom
    ports:
      - 7777:7777
      - 7778:7778
      - 7779:7779
    volumes:
      - vol_custom_conf_dir:/opt/iredmail/custom
    depends_on:
      - iredmail_mariadb
    networks:
      iredmail_net:
        aliases:
          - iredmail_iredapd
